[tool.black]
line-length = 79
target-version = ['py38']
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
(
    \.git
  | \.mypy_cache
  | \.pytest_cache
)
'''

[tool.isort]
default_section = 'THIRDPARTY'
sections = ['FUTURE' , 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
known_first_party = 'application'
atomic = true
indent = 4
line_length = 79
lines_after_imports = 2
multi_line_output = 3
include_trailing_comma = true
combine_as_imports = true
not_skip = '__init__.py'
force_grid_wrap = 0
skip_glob = []
skip = []
